// Static song-library metadata. MIDI musical data is still parsed exclusively by Rust WASM.
(() => {
  const catalog = [
  {
    "id": "later",
    "title": "后来",
    "subtitle": "经典版",
    "artist": "刘若英",
    "path": "music/后来_刘若英_C2_959553.mid",
    "duration": "04:13",
    "bpm": 75,
    "tone": "D♯",
    "rank": 0,
    "hue": 262,
    "theme": "later"
  },
  {
    "id": "later-advanced",
    "title": "后来",
    "subtitle": "进阶版",
    "artist": "刘若英",
    "path": "music/后来（进阶版）_刘若英_C2_298242.mid",
    "duration": "04:39",
    "bpm": 75,
    "tone": "D♯",
    "rank": 1,
    "hue": 278,
    "theme": "spectrum"
  },
  {
    "id": "moon",
    "title": "月亮代表我的心",
    "subtitle": "进阶版",
    "artist": "邓丽君",
    "path": "music/月亮代表我的心（进阶版）_邓丽君_C2_841537.mid",
    "duration": "03:23",
    "bpm": 78,
    "tone": "C♯",
    "rank": 2,
    "hue": 309,
    "theme": "moon"
  },
  {
    "id": "love-tide",
    "title": "爱如潮水",
    "subtitle": "进阶版",
    "artist": "张信哲",
    "path": "music/爱如潮水（进阶版）_张信哲_C2_060865.mid",
    "duration": "03:47",
    "bpm": 70,
    "tone": "E",
    "rank": 3,
    "hue": 340,
    "theme": "spectrum"
  },
  {
    "id": "ulan-night",
    "title": "乌兰巴托的夜",
    "subtitle": "进阶版",
    "artist": "丹正母子",
    "path": "music/乌兰巴托的夜（进阶版）_丹正母子_C2_330434.mid",
    "duration": "03:05",
    "bpm": 58,
    "tone": "D♯",
    "rank": 4,
    "hue": 11,
    "theme": "spectrum"
  },
  {
    "id": "rain-love",
    "title": "雨爱",
    "subtitle": "标准版",
    "artist": "杨丞琳",
    "path": "music/雨爱_杨丞琳_C2_359682.mid",
    "duration": "03:39",
    "bpm": 80,
    "tone": "E",
    "rank": 5,
    "hue": 42,
    "theme": "spectrum"
  },
  {
    "id": "chengdu",
    "title": "成都",
    "subtitle": "进阶版",
    "artist": "赵雷",
    "path": "music/成都（进阶版）_赵雷_C2_816194.mid",
    "duration": "09:53",
    "bpm": 91,
    "tone": "D",
    "rank": 6,
    "hue": 73,
    "theme": "spectrum"
  },
  {
    "id": "miss-you",
    "title": "我怀念的",
    "subtitle": "标准版",
    "artist": "孙燕姿",
    "path": "music/我怀念的_孙燕姿_C2_451009.mid",
    "duration": "04:24",
    "bpm": 70,
    "tone": "E",
    "rank": 7,
    "hue": 104,
    "theme": "spectrum"
  },
  {
    "id": "many-people",
    "title": "这世界那么多人",
    "subtitle": "进阶版",
    "artist": "莫文蔚",
    "path": "music/这世界那么多人（进阶版）_莫文蔚_C2_530882.mid",
    "duration": "04:38",
    "bpm": 72,
    "tone": "B",
    "rank": 8,
    "hue": 135,
    "theme": "spectrum"
  },
  {
    "id": "anhe-bridge",
    "title": "安和桥",
    "subtitle": "进阶版",
    "artist": "宋冬野",
    "path": "music/安和桥（进阶版）_宋冬野_C2_049538.mid",
    "duration": "04:01",
    "bpm": 65,
    "tone": "G",
    "rank": 9,
    "hue": 166,
    "theme": "spectrum"
  },
  {
    "id": "fairy-tale",
    "title": "童话",
    "subtitle": "标准版",
    "artist": "光良",
    "path": "music/童话_光良_C2_865730.mid",
    "duration": "03:42",
    "bpm": 68,
    "tone": "F♯",
    "rank": 10,
    "hue": 197,
    "theme": "spectrum"
  },
  {
    "id": "canon",
    "title": "卡农",
    "subtitle": "纯音乐",
    "artist": "纯音乐",
    "path": "music/卡农_纯音乐_C2_080194.mid",
    "duration": "03:36",
    "bpm": 80,
    "tone": "C",
    "rank": 11,
    "hue": 228,
    "theme": "spectrum"
  },
  {
    "id": "at-least-you",
    "title": "至少还有你",
    "subtitle": "进阶版",
    "artist": "林忆莲",
    "path": "music/至少还有你（进阶版）_林忆莲_C2_434433.mid",
    "duration": "04:23",
    "bpm": 62,
    "tone": "E",
    "rank": 12,
    "hue": 259,
    "theme": "spectrum"
  },
  {
    "id": "red-heels",
    "title": "红色高跟鞋",
    "subtitle": "进阶版",
    "artist": "蔡健雅",
    "path": "music/红色高跟鞋（进阶版）_蔡健雅_C2_226817.mid",
    "duration": "03:19",
    "bpm": 88,
    "tone": "D",
    "rank": 13,
    "hue": 290,
    "theme": "spectrum"
  },
  {
    "id": "wish",
    "title": "如愿",
    "subtitle": "进阶版",
    "artist": "王菲",
    "path": "music/如愿（进阶版）_王菲_C2_946241.mid",
    "duration": "04:10",
    "bpm": 66,
    "tone": "A",
    "rank": 14,
    "hue": 321,
    "theme": "spectrum"
  },
  {
    "id": "sunny-day",
    "title": "晴天",
    "subtitle": "进阶版",
    "artist": "周杰伦",
    "path": "music/晴天（进阶版）_周杰伦_C2_041026.mid",
    "duration": "04:27",
    "bpm": 68,
    "tone": "G",
    "rank": 15,
    "hue": 352,
    "theme": "spectrum"
  },
  {
    "id": "wind-rises",
    "title": "起风了",
    "subtitle": "进阶版",
    "artist": "买辣椒也用券",
    "path": "music/起风了（进阶版）_买辣椒也用券_C2_451137.mid",
    "duration": "05:07",
    "bpm": 77,
    "tone": "F♯",
    "rank": 16,
    "hue": 23,
    "theme": "spectrum"
  },
  {
    "id": "rice-fragrance",
    "title": "稻香",
    "subtitle": "进阶版",
    "artist": "周杰伦",
    "path": "music/稻香（进阶版）_周杰伦_C2_598209.mid",
    "duration": "03:28",
    "bpm": 82,
    "tone": "A",
    "rank": 17,
    "hue": 54,
    "theme": "spectrum"
  },
  {
    "id": "only-care-you",
    "title": "我只在乎你",
    "subtitle": "进阶版",
    "artist": "邓丽君",
    "path": "music/我只在乎你（进阶版）_邓丽君_C2_023234.mid",
    "duration": "03:53",
    "bpm": 70,
    "tone": "F",
    "rank": 18,
    "hue": 85,
    "theme": "spectrum"
  },
  {
    "id": "blue-white-porcelain",
    "title": "青花瓷",
    "subtitle": "进阶版",
    "artist": "周杰伦",
    "path": "music/青花瓷（进阶版）_周杰伦_C2_797761.mid",
    "duration": "03:49",
    "bpm": 54,
    "tone": "A",
    "rank": 19,
    "hue": 116,
    "theme": "spectrum"
  },
  {
    "id": "sea-and-you",
    "title": "海屿你",
    "subtitle": "标准版",
    "artist": "马也_Crabbit",
    "path": "music/海屿你_马也_Crabbit_C2_317953.mid",
    "duration": "04:42",
    "bpm": 75,
    "tone": "G♯",
    "rank": 20,
    "hue": 147,
    "theme": "spectrum"
  }
];
  window.FreezaSongCatalog = Object.freeze(catalog.map(item => Object.freeze(item)));
})();
